language: csharp

matrix:
  fast_finish: true

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq -f install
  - sudo apt-get -qq install emacs-snapshot
  - sudo apt-get -qq install emacs-snapshot-el

script:
  - make test-all

